import Head from "next/head";
import Link from "next/link";
import { FunctionComponent } from "react";
import styles from "../styles/Home.module.css";

const Layout: FunctionComponent = ({ children }) => {
  return (
    <>
      <Head>
        <title>Split.io Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {children}
        <ul>
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/static">Static</Link>
          </li>
          <li>
            <Link href="/ssg">SSG</Link>
          </li>
          <li>
            <Link href="/ssr">SSR</Link>
          </li>
        </ul>
      </main>
    </>
  );
};

export default Layout;
